### Loading all data

In [1]:
import pandas as pd
# Import csv files
df4 = pd.read_csv('week5_demographic_output.csv', encoding = 'unicode_escape' ) # Loading the demographics data
df2 = pd.read_csv('w8_prop_att.csv', encoding = 'unicode_escape' ) # Loading the property attributes data
df3 = pd.read_csv('week5_coastal_risk_output.csv', encoding = 'unicode_escape' ) # Loading the coastal risk 
df5 = pd.read_csv('week7_flood_risk_output_final.csv', encoding = 'unicode_escape' ) # Loading the flood risk
df1 = pd.read_csv('residential.csv', encoding = 'unicode_escape' ) # Loading the Address Fabrics with only residential properties

### Removing duplicates

In [2]:
# Check for duplicates in each DataFrame and display the number of duplicated rows
for i, df in enumerate([df1, df2, df3, df4, df5], start=1):
    duplicates = df[df.duplicated()]
    print(f"DataFrame df{i} - Number of duplicates: {len(duplicates)}")
    if len(duplicates) > 0:
        print(duplicates)

DataFrame df1 - Number of duplicates: 0
DataFrame df2 - Number of duplicates: 114715
                                        Address   preciselyID  yearBuilt  \
3            1320 E 5TH ST PANAMA CITY FL 32401           NaN        NaN
4            1320 E 5TH ST PANAMA CITY FL 32401           NaN        NaN
7            1320 E 5TH ST PANAMA CITY FL 32401           NaN        NaN
15           1320 E 5TH ST PANAMA CITY FL 32401           NaN        NaN
17           3818 E 8TH ST PANAMA CITY FL 32401  P00005L1N9LT     2021.0
...                                         ...           ...        ...
173278  1600 MARINA BAY DR PANAMA CITY FL 32409  P00005KA77WL        NaN
173279  1600 MARINA BAY DR PANAMA CITY FL 32409  P00005KA77WL        NaN
173280  1600 MARINA BAY DR PANAMA CITY FL 32409  P00005KA77WL        NaN
173281  1600 MARINA BAY DR PANAMA CITY FL 32409  P00005KA77WL        NaN
173307      100 MERRION RD PANAMA CITY FL 32409  P00005KO9ZO5     2019.0

        livingSquareFootage  bedroomCount  bathroomCount  saleAmount  \
3                       NaN           NaN            NaN         NaN
4                       NaN           NaN            NaN         NaN
7                       NaN           NaN            NaN         NaN
15                      NaN           NaN            NaN         NaN
17                  56716.0           2.0            2.0    460000.0
...                     ...           ...            ...         ...
173278                  NaN           NaN            NaN    600000.0
173279                  NaN           NaN            NaN    480000.0
173280                  NaN           NaN            NaN    425000.0
173281                  NaN           NaN            NaN     20000.0
173307               1697.0           4.0            2.0    320000.0

       interiorWallsValue                  interiorWallsDescription  \
3                     NaN                                       NaN
4                     NaN                                       NaN
7                     NaN                                       NaN
15                    NaN                                       NaN
17                      G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
...                   ...                                       ...
173278                NaN                                       NaN
173279                NaN                                       NaN
173280                NaN                                       NaN
173281                NaN                                       NaN
173307                  G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD

       exteriorWallsValue exteriorWallsDescription floorTypeValue  \
3                     NaN                      NaN            NaN
4                     NaN                      NaN            NaN
7                     NaN                      NaN            NaN
15                    NaN                      NaN            NaN
17                    OTH                    OTHER              V
...                   ...                      ...            ...
173278                NaN                      NaN            NaN
173279                NaN                      NaN            NaN
173280                NaN                      NaN            NaN
173281                NaN                      NaN            NaN
173307                IMI   SYNTHETIC PANEL/SIDING              V

       floorTypeDescription  roomCount roofCover  propertyAreaAcres  \
3                       NaN        NaN       NaN                NaN
4                       NaN        NaN       NaN                NaN
7                       NaN        NaN       NaN                NaN
15                      NaN        NaN       NaN                NaN
17                    VINYL        3.0   SHINGLE              4.316
...                     ...        ...       ...                ...
173278                  NaN        NaN       NaN              0.009
173279                  NaN        NaN       NaN              0.009
173280                  NaN        NaN       NaN              0.009
173281                  NaN        NaN       NaN              0.009
173307                VINYL        NaN   SHINGLE              0.218

        assessmentRecordingDate  totalAssessedValue
3                           NaN                 NaN
4                           NaN                 NaN
7                           NaN                 NaN
15                          NaN                 NaN
17                   20200629.0           4747195.0
...                         ...                 ...
173278               20230714.0              4336.0
173279               20230626.0             17001.0
173280               20210923.0              4336.0
173281               20220226.0              4336.0
173307               20220708.0            253699.0

[114715 rows x 18 columns]
DataFrame df3 - Number of duplicates: 31006
        preciselyID  distanceToNearestCoastFeet  waterbodyName
3      P00005KA743T                      3809.0            NaN
4      P00005KA743T                      3809.0            NaN
7      P00005KA743T                      3809.0            NaN
15     P00005KA743T                      3809.0            NaN
17     P00005L1N9LT                     10112.0            NaN
...             ...                         ...            ...
87709           NaN                         NaN            NaN
87710           NaN                         NaN            NaN
87711           NaN                         NaN            NaN
87714           NaN                         NaN            NaN
87719  P00005KO9ZO5                      2593.0            NaN

[31006 rows x 3 columns]
DataFrame df4 - Number of duplicates: 32561
        preciselyID PSYTEGroupCode  \
3      P00005KA743T             11
4      P00005KA743T             11
7      P00005KA743T             11
15     P00005KA743T             11
17     P00005L1N9LT              8
...             ...            ...
88073           NaN            NaN
88074           NaN            NaN
88075           NaN            NaN
88078           NaN            NaN
88083  P00005KO9ZO5             10

                propertyTenureVariableDescription  \
3                                    Mixed tenure
4                                    Mixed tenure
7                                    Mixed tenure
15                                   Mixed tenure
17     Majority of properties owned with mortgage
...                                           ...
88073                                         NaN
88074                                         NaN
88075                                         NaN
88078                                         NaN
88083  Majority of properties owned with mortgage

                             adultAgeVariableDescription
3      Majority of adult population aged 50+ and not ...
4      Majority of adult population aged 50+ and not ...
7      Majority of adult population aged 50+ and not ...
15     Majority of adult population aged 50+ and not ...
17     Majority of adult population aged under 29 (yo...
...                                                  ...
88073                                                NaN
88074                                                NaN
88075                                                NaN
88078                                                NaN
88083  Majority of adult population aged under 50 and...

[32561 rows x 4 columns]
DataFrame df5 - Number of duplicates: 31006
        preciselyID    floodID femaMapPanelIdentifier floodZoneMapType  \
3      P00005KA743T  6984537.0            12005C0342H              P2P
4      P00005KA743T  6984537.0            12005C0342H              P2P
7      P00005KA743T  6984537.0            12005C0342H              P2P
15     P00005KA743T  6984537.0            12005C0342H              P2P
17     P00005L1N9LT  6985531.0            12005C0361H              P2P
...             ...        ...                    ...              ...
87709           NaN        NaN                    NaN              NaN
87710           NaN        NaN                    NaN              NaN
87711           NaN        NaN                    NaN              NaN
87714           NaN        NaN                    NaN              NaN
87719  P00005KO9ZO5  6983691.0            12005C0218H              P2P

       stateFIPS floodZoneBaseFloodElevationFeet floodZone  \
3           12.0                          AE0008        AE
4           12.0                          AE0008        AE
7           12.0                          AE0008        AE
15          12.0                          AE0008        AE
17          12.0                               X         X
...          ...                             ...       ...
87709        NaN                             NaN       NaN
87710        NaN                             NaN       NaN
87711        NaN                             NaN       NaN
87714        NaN                             NaN       NaN
87719       12.0                        SHX-LOMR       SHX

      additionalInformation  baseFloodElevationFeet  communityNumber  ...  \
3                       NaN                     8.0         120012.0  ...
4                       NaN                     8.0         120012.0  ...
7                       NaN                     8.0         120012.0  ...
15                      NaN                     8.0         120012.0  ...
17                      NaN                     NaN         120014.0  ...
...                     ...                     ...              ...  ...
87709                   NaN                     NaN              NaN  ...
87710                   NaN                     NaN              NaN  ...
87711                   NaN                     NaN              NaN  ...
87714                   NaN                     NaN              NaN  ...
87719                  LOMR                     NaN         120004.0  ...

      letterOfMapRevisionDate letterOfMapRevisionCaseNumber  \
3                         NaN                           NaN
4                         NaN                           NaN
7                         NaN                           NaN
15                        NaN                           NaN
17                        NaN                           NaN
...                       ...                           ...
87709                     NaN                           NaN
87710                     NaN                           NaN
87711                     NaN                           NaN
87714                     NaN                           NaN
87719              2016-06-27                   15-04-8357P

      floodHazardBoundaryMapInitialDate floodInsuranceRateMapInitialDate  \
3                            1974-09-06                       1977-07-18
4                            1974-09-06                       1977-07-18
7                            1974-09-06                       1977-07-18
15                           1974-09-06                       1977-07-18
17                           1974-07-19                       1981-08-17
...                                 ...                              ...
87709                               NaN                              NaN
87710                               NaN                              NaN
87711                               NaN                              NaN
87714                               NaN                              NaN
87719                        1975-01-17                       1981-07-02

      addressLocationElevationFeet year100FloodZoneDistanceFeet  \
3                              3.0                          0.0
4                              3.0                          0.0
7                              3.0                          0.0
15                             3.0                          0.0
17                            27.0                        559.0
...                            ...                          ...
87709                          NaN                          NaN
87710                          NaN                          NaN
87711                          NaN                          NaN
87714                          NaN                          NaN
87719                          6.0                          7.0

       year500FloodZoneDistanceFeet  \
3                            4306.0
4                            4306.0
7                            4306.0
15                           4306.0
17                            519.0
...                             ...
87709                           NaN
87710                           NaN
87711                           NaN
87714                           NaN
87719                           0.0

                  elevationProfileToClosestWaterbodyFeet  \
3      3.85675, 18.62378, 27.08076, 27.85227, 27.2531...
4      3.85675, 18.62378, 27.08076, 27.85227, 27.2531...
7      3.85675, 18.62378, 27.08076, 27.85227, 27.2531...
15     3.85675, 18.62378, 27.08076, 27.85227, 27.2531...
17                                              27.22826
...                                                  ...
87709                                                NaN
87710                                                NaN
87711                                                NaN
87714                                                NaN
87719     6.43586, 4.52513, 0.71005, 0.71, 0.71, 2.09603

       distanceToNearestWaterbodyFeet nameOfNearestWaterbody
3                              2485.0                    NaN
4                              2485.0                    NaN
7                              2485.0                    NaN
15                             2485.0                    NaN
17                              438.0                    NaN
...                               ...                    ...
87709                             NaN                    NaN
87710                             NaN                    NaN
87711                             NaN                    NaN
87714                             NaN                    NaN
87719                          1297.0                    NaN

[31006 rows x 22 columns]

In [3]:
# Remove duplicates in each data frame
df3_unique = df3.drop_duplicates(keep='first')
df4_unique = df4.drop_duplicates(keep='first')
df2_unique = df2.drop_duplicates(keep='first')
df5_unique = df5.drop_duplicates(keep='first')

# df1 has no duplicate, therefore, we went ahead with other 4 dfs

print(df2_unique)
print(df3_unique)
print(df4_unique)
print(df5_unique)

                                         Address   preciselyID  yearBuilt  \
0             1320 E 5TH ST PANAMA CITY FL 32401           NaN        NaN
1             3818 E 8TH ST PANAMA CITY FL 32401  P00005L1N9LT     2021.0
2             316 CHERRY ST PANAMA CITY FL 32401  P00005KA73YZ     1982.0
5       665 1/2 CYPRESS AVE PANAMA CITY FL 32401           NaN        NaN
6          475 HARRISON AVE PANAMA CITY FL 32401  P00005KA73X0     1928.0
...                                          ...           ...        ...
173302        2301 MEGAN CT PANAMA CITY FL 32409           NaN        NaN
173303       7526 MARKET ST PANAMA CITY FL 32409           NaN        NaN
173304  1925 ANNA LAUREN DR PANAMA CITY FL 32409  P00005K4SWQ5     2004.0
173305  3822 FREDRICKSON ST PANAMA CITY FL 32409           NaN        NaN
173306     11702 RACCOON RD PANAMA CITY FL 32409           NaN        NaN

        livingSquareFootage  bedroomCount  bathroomCount  saleAmount  \
0                       NaN           NaN            NaN         NaN
1                   56716.0           2.0            2.0    460000.0
2                     860.0           2.0            2.0         NaN
5                       NaN           NaN            NaN         NaN
6                   10500.0           NaN            NaN    925000.0
...                     ...           ...            ...         ...
173302                  NaN           NaN            NaN         NaN
173303                  NaN           NaN            NaN         NaN
173304               2280.0           4.0            2.0     65000.0
173305                  NaN           NaN            NaN         NaN
173306                  NaN           NaN            NaN         NaN

       interiorWallsValue                  interiorWallsDescription  \
0                     NaN                                       NaN
1                       G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
2                     NaN                                       NaN
5                     NaN                                       NaN
6                       H                         DECORATIVE/CUSTOM
...                   ...                                       ...
173302                NaN                                       NaN
173303                NaN                                       NaN
173304                  G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
173305                NaN                                       NaN
173306                NaN                                       NaN

       exteriorWallsValue exteriorWallsDescription floorTypeValue  \
0                     NaN                      NaN            NaN
1                     OTH                    OTHER              V
2                     NaN                      NaN            NaN
5                     NaN                      NaN            NaN
6                     MIX                  MIXTURE             PT
...                   ...                      ...            ...
173302                NaN                      NaN            NaN
173303                NaN                      NaN            NaN
173304                OTH                    OTHER             PV
173305                NaN                      NaN            NaN
173306                NaN                      NaN            NaN

       floorTypeDescription  roomCount roofCover  propertyAreaAcres  \
0                       NaN        NaN       NaN                NaN
1                     VINYL        3.0   SHINGLE           4.316000
2                       NaN        NaN       NaN           1.337006
5                       NaN        NaN       NaN                NaN
6                       NaN       25.0     OTHER           0.193000
...                     ...        ...       ...                ...
173302                  NaN        NaN       NaN                NaN
173303                  NaN        NaN       NaN                NaN
173304                  NaN        NaN   SHINGLE           1.052000
173305                  NaN        NaN       NaN                NaN
173306                  NaN        NaN       NaN                NaN

        assessmentRecordingDate  totalAssessedValue
0                           NaN                 NaN
1                    20200629.0           4747195.0
2                           NaN                 1.0
5                           NaN                 NaN
6                    20190918.0            630161.0
...                         ...                 ...
173302                      NaN                 NaN
173303                      NaN                 NaN
173304               20180530.0             68530.0
173305                      NaN                 NaN
173306                      NaN                 NaN

[58593 rows x 18 columns]
        preciselyID  distanceToNearestCoastFeet  waterbodyName
0      P00005KA743T                      3809.0            NaN
1      P00005L1N9LT                     10112.0            NaN
2      P00005KA73YZ                       214.0            NaN
5      P00005K4RK9C                      3758.0            NaN
6      P00005KA73X0                      1072.0            NaN
...             ...                         ...            ...
87713  P00005K9QQ9H                     12342.0            NaN
87715  P00005L1DIT0                      5618.0            NaN
87716  P00005K4SWQ5                     40820.0            NaN
87717  P00005K9QQE6                     20469.0            NaN
87718  P00005KPGMJX                     34777.0            NaN

[56714 rows x 3 columns]
        preciselyID PSYTEGroupCode  \
0      P00005KA743T             11
1      P00005L1N9LT              8
2      P00005KA73YZ              5
5      P00005K4RK9C             11
6      P00005KA73X0             NC
...             ...            ...
88077  P00005K9QQ9H              9
88079  P00005L1DIT0              9
88080  P00005K4SWQ5             10
88081  P00005K9QQE6              7
88082  P00005KPGMJX             10

                propertyTenureVariableDescription  \
0                                    Mixed tenure
1      Majority of properties owned with mortgage
2      Majority of properties owned with mortgage
5                                    Mixed tenure
6                                  Not Classified
...                                           ...
88077       Majority of properties owned outright
88079       Majority of properties owned outright
88080  Majority of properties owned with mortgage
88081  Majority of properties owned with mortgage
88082  Majority of properties owned with mortgage

                             adultAgeVariableDescription
0      Majority of adult population aged 50+ and not ...
1      Majority of adult population aged under 29 (yo...
2        Majority of adult population aged 65+ (retired)
5      Majority of adult population aged under 50 and...
6                                         Not Classified
...                                                  ...
88077  Majority of adult population aged 40-59 (middl...
88079  Majority of adult population aged 40-59 (middl...
88080  Majority of adult population aged under 50 and...
88081  Majority of adult population aged 40-59 (middl...
88082  Majority of adult population aged under 50 and...

[55523 rows x 4 columns]
        preciselyID    floodID femaMapPanelIdentifier floodZoneMapType  \
0      P00005KA743T  6984537.0            12005C0342H              P2P
1      P00005L1N9LT  6985531.0            12005C0361H              P2P
2      P00005KA73YZ  6987238.0            12005C0344H              P2P
5      P00005K4RK9C  6988163.0            12005C0342H              P2P
6      P00005KA73X0  6983588.0            12005C0341H              P2P
...             ...        ...                    ...              ...
87713  P00005K9QQ9H  6983518.0            12005C0185H              P2P
87715  P00005L1DIT0  6990530.0            12005C0220H              P2P
87716  P00005K4SWQ5  6983381.0            12005C0090H              P2P
87717  P00005K9QQE6  6994357.0            12005C0240H              P2P
87718  P00005KPGMJX  6983430.0            12005C0210H              P2P

       stateFIPS floodZoneBaseFloodElevationFeet floodZone  \
0           12.0                          AE0008        AE
1           12.0                               X         X
2           12.0                               X         X
5           12.0                               X         X
6           12.0                               X         X
...          ...                             ...       ...
87713       12.0                               X         X
87715       12.0                          AE0007        AE
87716       12.0                               X         X
87717       12.0                               X         X
87718       12.0                               X         X

      additionalInformation  baseFloodElevationFeet  communityNumber  ...  \
0                       NaN                     8.0         120012.0  ...
1                       NaN                     NaN         120014.0  ...
2                       NaN                     NaN         120012.0  ...
5                       NaN                     NaN         120012.0  ...
6                       NaN                     NaN         120012.0  ...
...                     ...                     ...              ...  ...
87713                   NaN                     NaN         120004.0  ...
87715                   NaN                     7.0         120004.0  ...
87716                   NaN                     NaN         120004.0  ...
87717                   NaN                     NaN         120004.0  ...
87718                   NaN                     NaN         120004.0  ...

      letterOfMapRevisionDate letterOfMapRevisionCaseNumber  \
0                         NaN                           NaN
1                         NaN                           NaN
2                         NaN                           NaN
5                         NaN                           NaN
6                         NaN                           NaN
...                       ...                           ...
87713                     NaN                           NaN
87715                     NaN                           NaN
87716                     NaN                           NaN
87717                     NaN                           NaN
87718                     NaN                           NaN

      floodHazardBoundaryMapInitialDate floodInsuranceRateMapInitialDate  \
0                            1974-09-06                       1977-07-18
1                            1974-07-19                       1981-08-17
2                            1974-09-06                       1977-07-18
5                            1974-09-06                       1977-07-18
6                            1974-09-06                       1977-07-18
...                                 ...                              ...
87713                        1975-01-17                       1981-07-02
87715                        1975-01-17                       1981-07-02
87716                        1975-01-17                       1981-07-02
87717                        1975-01-17                       1981-07-02
87718                        1975-01-17                       1981-07-02

      addressLocationElevationFeet year100FloodZoneDistanceFeet  \
0                              3.0                          0.0
1                             27.0                        559.0
2                             17.0                        134.0
5                             18.0                         85.0
6                             21.0                        370.0
...                            ...                          ...
87713                         13.0                         11.0
87715                          5.0                          0.0
87716                         88.0                       2917.0
87717                         14.0                         98.0
87718                         73.0                         52.0

       year500FloodZoneDistanceFeet  \
0                            4306.0
1                             519.0
2                            3812.0
5                            3470.0
6                         -999999.0
...                             ...
87713                     -999999.0
87715                        3937.0
87716                        1206.0
87717                     -999999.0
87718                     -999999.0

                  elevationProfileToClosestWaterbodyFeet  \
0      3.85675, 18.62378, 27.08076, 27.85227, 27.2531...
1                                               27.22826
2                                               17.15681
5                    18.01729, 7.18895, 0, 0, 1.87483, 0
6                                               21.09787
...                                                  ...
87713                                            13.2155
87715                  5.34616, 7.4941, 8.13801, 0.73106
87716    88.6871, 90.31115, 92.54044, 87.61246, 62.37803
87717     14.60559, 16.33918, 13.50817, 7.93282, 4.55684
87718  73.20064, 76.14167, 78.81424, 79.61158, 78.431...

       distanceToNearestWaterbodyFeet nameOfNearestWaterbody
0                              2485.0                    NaN
1                               438.0                    NaN
2                              6692.0                    NaN
5                              1387.0                    NaN
6                              5941.0                    NaN
...                               ...                    ...
87713                           359.0       Burnt Mill Creek
87715                           787.0                    NaN
87716                          1224.0      Clearwater Branch
87717                          1017.0                    NaN
87718                          5216.0                    NaN

[56714 rows x 22 columns]

### Removing NaN rows

In [4]:
# Remove rows where 'preciselyID' is NaN in each data frame, because when 'preciselyID' is NaN, all other columns will be NaN
df2_unique = df2_unique.dropna(subset=['preciselyID'])
df3_unique = df3_unique.dropna(subset=['preciselyID'])
df4_unique = df4_unique.dropna(subset=['preciselyID'])
df5_unique = df5_unique.dropna(subset=['preciselyID'])


# Verify by displaying the first few rows
print(df2_unique)
print(df3_unique)
print(df4_unique)
print(df5_unique)
print(df1)

                                             Address   preciselyID  yearBuilt  \
1                 3818 E 8TH ST PANAMA CITY FL 32401  P00005L1N9LT     2021.0
2                 316 CHERRY ST PANAMA CITY FL 32401  P00005KA73YZ     1982.0
6              475 HARRISON AVE PANAMA CITY FL 32401  P00005KA73X0     1928.0
9          1450 N PALO ALTO AVE PANAMA CITY FL 32401  P00005L2IRJ5     1955.0
10               1032 W 12TH CT PANAMA CITY FL 32401  P00005K4RJEP     1955.0
...                                              ...           ...        ...
173251  7001 DE AURRECOECHEA DR PANAMA CITY FL 32409  P00005KAHOXE     1973.0
173282          7811 WALTON AVE PANAMA CITY FL 32409  P00005K4SX3Z     1966.0
173287             82 ALEGRO DR PANAMA CITY FL 32409  P00005KH5HIS     2017.0
173300        7639 OLDE MILL RD PANAMA CITY FL 32409  P00005K4SYN1     1977.0
173304      1925 ANNA LAUREN DR PANAMA CITY FL 32409  P00005K4SWQ5     2004.0

        livingSquareFootage  bedroomCount  bathroomCount  saleAmount  \
1                   56716.0           2.0            2.0    460000.0
2                     860.0           2.0            2.0         NaN
6                   10500.0           NaN            NaN    925000.0
9                    4550.0          20.0            NaN         NaN
10                   2116.0           3.0            2.0    213000.0
...                     ...           ...            ...         ...
173251               6641.0           5.0            2.5    125000.0
173282               1564.0           3.0            1.0     17500.0
173287               2939.0           4.0            3.0    376900.0
173300               2360.0           3.0            2.0         NaN
173304               2280.0           4.0            2.0     65000.0

       interiorWallsValue                  interiorWallsDescription  \
1                       G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
2                     NaN                                       NaN
6                       H                         DECORATIVE/CUSTOM
9                     NaN                                       NaN
10                      G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
...                   ...                                       ...
173251                  G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
173282                  G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
173287                  G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
173300                  G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
173304                  G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD

       exteriorWallsValue     exteriorWallsDescription floorTypeValue  \
1                     OTH                        OTHER              V
2                     NaN                          NaN            NaN
6                     MIX                      MIXTURE             PT
9                     BRI                        BRICK            NaN
10                    STU                       STUCCO             PV
...                   ...                          ...            ...
173251                CNB               CONCRETE BLOCK              C
173282                CNB               CONCRETE BLOCK             VH
173287                BBS  BRICK/CONCRETE BLOCK STUCCO             TP
173300                STU                       STUCCO             VP
173304                OTH                        OTHER             PV

       floorTypeDescription  roomCount         roofCover  propertyAreaAcres  \
1                     VINYL        3.0           SHINGLE           4.316000
2                       NaN        NaN               NaN           1.337006
6                       NaN       25.0             OTHER           0.193000
9                       NaN       21.0     MODULAR METAL           8.000000
10                      NaN        NaN  COMPOSITION ROLL           0.241000
...                     ...        ...               ...                ...
173251             CONCRETE        6.0           SHINGLE           4.501900
173282                  NaN        NaN             METAL           2.066000
173287                  NaN        NaN           SHINGLE           0.350000
173300                  NaN        NaN           SHINGLE           3.622000
173304                  NaN        NaN           SHINGLE           1.052000

        assessmentRecordingDate  totalAssessedValue
1                    20200629.0           4747195.0
2                           NaN                 1.0
6                    20190918.0            630161.0
9                    20211109.0            320000.0
10                   20200306.0            212863.0
...                         ...                 ...
173251               20170127.0            381335.0
173282               20000907.0             84275.0
173287               20171201.0            354226.0
173300               20030722.0            139974.0
173304               20180530.0             68530.0

[50296 rows x 18 columns]
        preciselyID  distanceToNearestCoastFeet  waterbodyName
0      P00005KA743T                      3809.0            NaN
1      P00005L1N9LT                     10112.0            NaN
2      P00005KA73YZ                       214.0            NaN
5      P00005K4RK9C                      3758.0            NaN
6      P00005KA73X0                      1072.0            NaN
...             ...                         ...            ...
87713  P00005K9QQ9H                     12342.0            NaN
87715  P00005L1DIT0                      5618.0            NaN
87716  P00005K4SWQ5                     40820.0            NaN
87717  P00005K9QQE6                     20469.0            NaN
87718  P00005KPGMJX                     34777.0            NaN

[56713 rows x 3 columns]
        preciselyID PSYTEGroupCode  \
0      P00005KA743T             11
1      P00005L1N9LT              8
2      P00005KA73YZ              5
5      P00005K4RK9C             11
6      P00005KA73X0             NC
...             ...            ...
88077  P00005K9QQ9H              9
88079  P00005L1DIT0              9
88080  P00005K4SWQ5             10
88081  P00005K9QQE6              7
88082  P00005KPGMJX             10

                propertyTenureVariableDescription  \
0                                    Mixed tenure
1      Majority of properties owned with mortgage
2      Majority of properties owned with mortgage
5                                    Mixed tenure
6                                  Not Classified
...                                           ...
88077       Majority of properties owned outright
88079       Majority of properties owned outright
88080  Majority of properties owned with mortgage
88081  Majority of properties owned with mortgage
88082  Majority of properties owned with mortgage

                             adultAgeVariableDescription
0      Majority of adult population aged 50+ and not ...
1      Majority of adult population aged under 29 (yo...
2        Majority of adult population aged 65+ (retired)
5      Majority of adult population aged under 50 and...
6                                         Not Classified
...                                                  ...
88077  Majority of adult population aged 40-59 (middl...
88079  Majority of adult population aged 40-59 (middl...
88080  Majority of adult population aged under 50 and...
88081  Majority of adult population aged 40-59 (middl...
88082  Majority of adult population aged under 50 and...

[55522 rows x 4 columns]
        preciselyID    floodID femaMapPanelIdentifier floodZoneMapType  \
0      P00005KA743T  6984537.0            12005C0342H              P2P
1      P00005L1N9LT  6985531.0            12005C0361H              P2P
2      P00005KA73YZ  6987238.0            12005C0344H              P2P
5      P00005K4RK9C  6988163.0            12005C0342H              P2P
6      P00005KA73X0  6983588.0            12005C0341H              P2P
...             ...        ...                    ...              ...
87713  P00005K9QQ9H  6983518.0            12005C0185H              P2P
87715  P00005L1DIT0  6990530.0            12005C0220H              P2P
87716  P00005K4SWQ5  6983381.0            12005C0090H              P2P
87717  P00005K9QQE6  6994357.0            12005C0240H              P2P
87718  P00005KPGMJX  6983430.0            12005C0210H              P2P

       stateFIPS floodZoneBaseFloodElevationFeet floodZone  \
0           12.0                          AE0008        AE
1           12.0                               X         X
2           12.0                               X         X
5           12.0                               X         X
6           12.0                               X         X
...          ...                             ...       ...
87713       12.0                               X         X
87715       12.0                          AE0007        AE
87716       12.0                               X         X
87717       12.0                               X         X
87718       12.0                               X         X

      additionalInformation  baseFloodElevationFeet  communityNumber  ...  \
0                       NaN                     8.0         120012.0  ...
1                       NaN                     NaN         120014.0  ...
2                       NaN                     NaN         120012.0  ...
5                       NaN                     NaN         120012.0  ...
6                       NaN                     NaN         120012.0  ...
...                     ...                     ...              ...  ...
87713                   NaN                     NaN         120004.0  ...
87715                   NaN                     7.0         120004.0  ...
87716                   NaN                     NaN         120004.0  ...
87717                   NaN                     NaN         120004.0  ...
87718                   NaN                     NaN         120004.0  ...

      letterOfMapRevisionDate letterOfMapRevisionCaseNumber  \
0                         NaN                           NaN
1                         NaN                           NaN
2                         NaN                           NaN
5                         NaN                           NaN
6                         NaN                           NaN
...                       ...                           ...
87713                     NaN                           NaN
87715                     NaN                           NaN
87716                     NaN                           NaN
87717                     NaN                           NaN
87718                     NaN                           NaN

      floodHazardBoundaryMapInitialDate floodInsuranceRateMapInitialDate  \
0                            1974-09-06                       1977-07-18
1                            1974-07-19                       1981-08-17
2                            1974-09-06                       1977-07-18
5                            1974-09-06                       1977-07-18
6                            1974-09-06                       1977-07-18
...                                 ...                              ...
87713                        1975-01-17                       1981-07-02
87715                        1975-01-17                       1981-07-02
87716                        1975-01-17                       1981-07-02
87717                        1975-01-17                       1981-07-02
87718                        1975-01-17                       1981-07-02

      addressLocationElevationFeet year100FloodZoneDistanceFeet  \
0                              3.0                          0.0
1                             27.0                        559.0
2                             17.0                        134.0
5                             18.0                         85.0
6                             21.0                        370.0
...                            ...                          ...
87713                         13.0                         11.0
87715                          5.0                          0.0
87716                         88.0                       2917.0
87717                         14.0                         98.0
87718                         73.0                         52.0

       year500FloodZoneDistanceFeet  \
0                            4306.0
1                             519.0
2                            3812.0
5                            3470.0
6                         -999999.0
...                             ...
87713                     -999999.0
87715                        3937.0
87716                        1206.0
87717                     -999999.0
87718                     -999999.0

                  elevationProfileToClosestWaterbodyFeet  \
0      3.85675, 18.62378, 27.08076, 27.85227, 27.2531...
1                                               27.22826
2                                               17.15681
5                    18.01729, 7.18895, 0, 0, 1.87483, 0
6                                               21.09787
...                                                  ...
87713                                            13.2155
87715                  5.34616, 7.4941, 8.13801, 0.73106
87716    88.6871, 90.31115, 92.54044, 87.61246, 62.37803
87717     14.60559, 16.33918, 13.50817, 7.93282, 4.55684
87718  73.20064, 76.14167, 78.81424, 79.61158, 78.431...

       distanceToNearestWaterbodyFeet nameOfNearestWaterbody
0                              2485.0                    NaN
1                               438.0                    NaN
2                              6692.0                    NaN
5                              1387.0                    NaN
6                              5941.0                    NaN
...                               ...                    ...
87713                           359.0       Burnt Mill Creek
87715                           787.0                    NaN
87716                          1224.0      Clearwater Branch
87717                          1017.0                    NaN
87718                          5216.0                    NaN

[56713 rows x 22 columns]
        preciselyID ADD_NUMBER      STREETNAME UNIT_DES UNIT_NUM         CITY  \
0      P00005K4RN73       1320        E 5TH ST      APT      208  PANAMA CITY
1      P00005L1N9KX       3818        E 8TH ST      APT     2105  PANAMA CITY
2      P00005K4RESU        316       CHERRY ST      APT       24  PANAMA CITY
3      P00005K4RN7D       1320        E 5TH ST      APT      310  PANAMA CITY
4      P00005K4RN7B       1320        E 5TH ST      APT      308  PANAMA CITY
...             ...        ...             ...      ...      ...          ...
88079  P00005L1DIT0       7526       MARKET ST      NaN      NaN  PANAMA CITY
88080  P00005K4SWQ5       1925  ANNA LAUREN DR      NaN      NaN  PANAMA CITY
88081  P00005K9QQE6       3822  FREDRICKSON ST      NaN      NaN  PANAMA CITY
88082  P00005KPGMJX      11702      RACCOON RD      NaN      NaN  PANAMA CITY
88083  P00005KO9ZO5        100      MERRION RD      NaN      NaN  PANAMA CITY

      STATE  ZIPCODE   PLUS4 LOC_CODE         GEOID        LAT        LON  \
0        FL    32401  4377.0      P05  1.200000e+14  30.156902 -85.641168
1        FL    32401  6260.0      P02  1.200000e+14  30.163293 -85.609253
2        FL    32401  3205.0      P05  1.200000e+14  30.145700 -85.654969
3        FL    32401  4378.0      P05  1.200000e+14  30.156902 -85.641168
4        FL    32401  4378.0      P05  1.200000e+14  30.156902 -85.641168
...     ...      ...     ...      ...           ...        ...        ...
88079    FL    32409  3337.0      P02  1.200000e+14  30.286983 -85.642878
88080    FL    32409  3566.0      P05  1.200000e+14  30.403149 -85.722133
88081    FL    32409  4015.0      P02  1.200000e+14  30.308553 -85.601466
88082    FL    32409  2600.0      P02  1.200000e+14  30.370049 -85.649841
88083    FL    32409  1768.0      P05  1.200000e+14  30.274796 -85.668763

             PARENT PROP_TYPE   FIPS
0      P00005KA743T         R  12005
1      P00005L1N9LT         R  12005
2      P00005KA73YZ         R  12005
3      P00005KA743T         R  12005
4      P00005KA743T         R  12005
...             ...       ...    ...
88079           NaN         R  12005
88080           NaN         R  12005
88081           NaN         R  12005
88082           NaN         R  12005
88083           NaN         R  12005

[88084 rows x 16 columns]

### Keep updated sale record for each preciselyID

#### One precisely ID can have multiple sales records over time, we based on the 'assessmentRecordingDate' to keep only the latest record

In [5]:
## Keep only the latest record for each preciselyID on Property attributes

# Convert 'assessmentRecordingDate' to string and remove any decimal places if they exist
df2_unique['assessmentRecordingDate'] = df2_unique['assessmentRecordingDate'].astype(str).str.replace('.0', '', regex=False)

# Convert the column to datetime format using the specified format
df2_unique['assessmentRecordingDate'] = pd.to_datetime(df2_unique['assessmentRecordingDate'], format='%Y%m%d')

# Finally, change the date format to MM/DD/YYYY
df2_unique['assessmentRecordingDate'] = df2_unique['assessmentRecordingDate'].dt.strftime('%m/%d/%Y')

# Sort by preciselyID and assessmentRecordingDate in ascending order
df2_unique = df2_unique.sort_values(by=['preciselyID', 'assessmentRecordingDate'])

# Drop duplicates based on preciselyID, keeping the last occurrence (most recent date)
df2_unique = df2_unique.drop_duplicates(subset=['preciselyID'], keep='last')

# Verify by displaying the resulting DataFrame
print("DataFrame after keeping rows with the most recent assessmentRecordingDate for each preciselyID:")
print(df2_unique)

DataFrame after keeping rows with the most recent assessmentRecordingDate for each preciselyID:
                                         Address   preciselyID  yearBuilt  \
11505       102 N COVE BLVD PANAMA CITY FL 32401  P00005K4RE4I     1950.0
3313        106 N COVE BLVD PANAMA CITY FL 32401  P00005K4RE4J     1942.0
6673        110 N COVE BLVD PANAMA CITY FL 32401  P00005K4RE4K     1940.0
6622        116 N COVE BLVD PANAMA CITY FL 32401  P00005K4RE4L     1947.0
13081       120 N COVE BLVD PANAMA CITY FL 32401  P00005K4RE4M     1941.0
...                                          ...           ...        ...
63267   2311 DISCOVERY LOOP PANAMA CITY FL 32405  P00005L3PC7T        NaN
61205   2331 DISCOVERY LOOP PANAMA CITY FL 32405  P00005L3PC7U        NaN
62895     3238 SWEETBAY AVE PANAMA CITY FL 32405  P00005L3PC86        NaN
61012     3246 SWEETBAY AVE PANAMA CITY FL 32405  P00005L3PC87        NaN
162759         77 GULF LOOP PANAMA CITY FL 32408  P00005L3TH6Z     2017.0

        livingSquareFootage  bedroomCount  bathroomCount  saleAmount  \
11505                2090.0           3.0            2.0    345000.0
3313                 1406.0           3.0            2.0    265000.0
6673                 1872.0           4.0            2.5    270000.0
6622                 1264.0           3.0            1.5     88500.0
13081                1417.0           3.0            2.0    250000.0
...                     ...           ...            ...         ...
63267                   NaN           NaN            NaN         NaN
61205                   NaN           NaN            NaN         NaN
62895                   NaN           NaN            NaN         NaN
61012                   NaN           NaN            NaN         NaN
162759                788.0           2.0            1.0    270000.0

       interiorWallsValue                  interiorWallsDescription  \
11505                   G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
3313                    G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
6673                    G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
6622                    G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
13081                   G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD
...                   ...                                       ...
63267                 NaN                                       NaN
61205                 NaN                                       NaN
62895                 NaN                                       NaN
61012                 NaN                                       NaN
162759                  G  GYPSUM BOARD/DRYWALL/SHEETROCK/WALLBOARD

       exteriorWallsValue     exteriorWallsDescription floorTypeValue  \
11505                 BBS  BRICK/CONCRETE BLOCK STUCCO             WP
3313                  OTH                        OTHER              T
6673                  IMI       SYNTHETIC PANEL/SIDING             TW
6622                  CNB               CONCRETE BLOCK             WP
13081                 IMI       SYNTHETIC PANEL/SIDING             VP
...                   ...                          ...            ...
63267                 NaN                          NaN            NaN
61205                 NaN                          NaN            NaN
62895                 NaN                          NaN            NaN
61012                 NaN                          NaN            NaN
162759                IMI       SYNTHETIC PANEL/SIDING              P

       floorTypeDescription  roomCount roofCover  propertyAreaAcres  \
11505                   NaN        NaN   SHINGLE              0.482
3313                   TILE        NaN     METAL              0.241
6673                    NaN        NaN   SHINGLE              0.321
6622                    NaN        NaN   SHINGLE              0.321
13081                   NaN        NaN   SHINGLE              0.241
...                     ...        ...       ...                ...
63267                   NaN        NaN       NaN              0.091
61205                   NaN        NaN       NaN              0.091
62895                   NaN        NaN       NaN              0.066
61012                   NaN        NaN       NaN              0.057
162759               CARPET        NaN   SHINGLE              0.041

       assessmentRecordingDate  totalAssessedValue
11505               02/18/2022            299597.0
3313                12/30/2021            228892.0
6673                04/09/2021            252923.0
6622                12/15/2000            122364.0
13081               03/11/1999             55241.0
...                        ...                 ...
63267               04/12/2023              9203.0
61205               04/12/2023              9203.0
62895               04/12/2023              9203.0
61012               04/12/2023              9203.0
162759              08/12/2020            235347.0

[49565 rows x 18 columns]

### Merging all data in 1 file

In [6]:
# Merge the DataFrames based on preciselyID
merged_df = pd.merge(df1, df2_unique, on="preciselyID", how = "left")
merged_df2 = pd.merge(merged_df, df3_unique, on="preciselyID", how = "left")
merged_df3 = pd.merge(merged_df2, df4_unique, on="preciselyID", how="left")
merged_df4 = pd.merge(merged_df3, df5_unique, on="preciselyID", how="left")

# Specify columns to keep
columns_to_keep = [
    "propertyAreaAcres",
    "year100FloodZoneDistanceFeet",
    "distanceToNearestCoastFeet",
    "livingSquareFootage",
    "totalAssessedValue",
    "saleAmount",
    "yearBuilt",
    "addressLocationElevationFeet",
    "adultAgeVariableDescription",
    "PSYTEGroupCode",
    "propertyTenureVariableDescription",
    "roofCover"
]

# Get all columns from df1 and combine with the columns_to_keep
final_columns = df1.columns.tolist() + columns_to_keep

# Filter the merged DataFrame to retain only the specified columns
merged_df4 = merged_df4[final_columns]

# Display the filtered DataFrame
print("Merged DataFrame:")
print(merged_df4)

Merged DataFrame:
        preciselyID ADD_NUMBER      STREETNAME UNIT_DES UNIT_NUM         CITY  \
0      P00005K4RN73       1320        E 5TH ST      APT      208  PANAMA CITY
1      P00005L1N9KX       3818        E 8TH ST      APT     2105  PANAMA CITY
2      P00005K4RESU        316       CHERRY ST      APT       24  PANAMA CITY
3      P00005K4RN7D       1320        E 5TH ST      APT      310  PANAMA CITY
4      P00005K4RN7B       1320        E 5TH ST      APT      308  PANAMA CITY
...             ...        ...             ...      ...      ...          ...
88079  P00005L1DIT0       7526       MARKET ST      NaN      NaN  PANAMA CITY
88080  P00005K4SWQ5       1925  ANNA LAUREN DR      NaN      NaN  PANAMA CITY
88081  P00005K9QQE6       3822  FREDRICKSON ST      NaN      NaN  PANAMA CITY
88082  P00005KPGMJX      11702      RACCOON RD      NaN      NaN  PANAMA CITY
88083  P00005KO9ZO5        100      MERRION RD      NaN      NaN  PANAMA CITY

      STATE  ZIPCODE   PLUS4 LOC_CODE  ...  distanceToNearestCoastFeet  \
0        FL    32401  4377.0      P05  ...                         NaN
1        FL    32401  6260.0      P02  ...                         NaN
2        FL    32401  3205.0      P05  ...                         NaN
3        FL    32401  4378.0      P05  ...                         NaN
4        FL    32401  4378.0      P05  ...                         NaN
...     ...      ...     ...      ...  ...                         ...
88079    FL    32409  3337.0      P02  ...                      5618.0
88080    FL    32409  3566.0      P05  ...                     40820.0
88081    FL    32409  4015.0      P02  ...                     20469.0
88082    FL    32409  2600.0      P02  ...                     34777.0
88083    FL    32409  1768.0      P05  ...                      2593.0

       livingSquareFootage  totalAssessedValue saleAmount yearBuilt  \
0                      NaN                 NaN        NaN       NaN
1                      NaN                 NaN        NaN       NaN
2                      NaN                 NaN        NaN       NaN
3                      NaN                 NaN        NaN       NaN
4                      NaN                 NaN        NaN       NaN
...                    ...                 ...        ...       ...
88079                  NaN                 NaN        NaN       NaN
88080               2280.0             68530.0    65000.0    2004.0
88081                  NaN                 NaN        NaN       NaN
88082                  NaN                 NaN        NaN       NaN
88083               1697.0            253699.0   320000.0    2019.0

       addressLocationElevationFeet  \
0                               NaN
1                               NaN
2                               NaN
3                               NaN
4                               NaN
...                             ...
88079                           5.0
88080                          88.0
88081                          14.0
88082                          73.0
88083                           6.0

                             adultAgeVariableDescription  PSYTEGroupCode  \
0                                                    NaN             NaN
1                                                    NaN             NaN
2                                                    NaN             NaN
3                                                    NaN             NaN
4                                                    NaN             NaN
...                                                  ...             ...
88079  Majority of adult population aged 40-59 (middl...               9
88080  Majority of adult population aged under 50 and...              10
88081  Majority of adult population aged 40-59 (middl...               7
88082  Majority of adult population aged under 50 and...              10
88083  Majority of adult population aged under 50 and...              10

                propertyTenureVariableDescription  roofCover
0                                             NaN        NaN
1                                             NaN        NaN
2                                             NaN        NaN
3                                             NaN        NaN
4                                             NaN        NaN
...                                           ...        ...
88079       Majority of properties owned outright        NaN
88080  Majority of properties owned with mortgage    SHINGLE
88081  Majority of properties owned with mortgage        NaN
88082  Majority of properties owned with mortgage        NaN
88083  Majority of properties owned with mortgage    SHINGLE

[88084 rows x 28 columns]

In [7]:
# Filter out rows where all specified columns are NaN
filtered_merged_df4 = merged_df4.dropna(subset=columns_to_keep, how='all')

# Display the filtered DataFrame
print("Filtered Merged DataFrame without rows where all specified columns are NaN:")
print(filtered_merged_df4)

Filtered Merged DataFrame without rows where all specified columns are NaN:
        preciselyID ADD_NUMBER      STREETNAME UNIT_DES UNIT_NUM         CITY  \
5      P00005K4RK9C    665 1/2     CYPRESS AVE      NaN      NaN  PANAMA CITY
8      P00005K4RKAF        604         BAY AVE      NaN      NaN  PANAMA CITY
10     P00005K4RJEP       1032       W 12TH CT      NaN      NaN  PANAMA CITY
11     P00005K4RNZG       1407        E 6TH CT      NaN      NaN  PANAMA CITY
12     P00005K4RKMU       1010      W BEACH DR      NaN      NaN  PANAMA CITY
...             ...        ...             ...      ...      ...          ...
88079  P00005L1DIT0       7526       MARKET ST      NaN      NaN  PANAMA CITY
88080  P00005K4SWQ5       1925  ANNA LAUREN DR      NaN      NaN  PANAMA CITY
88081  P00005K9QQE6       3822  FREDRICKSON ST      NaN      NaN  PANAMA CITY
88082  P00005KPGMJX      11702      RACCOON RD      NaN      NaN  PANAMA CITY
88083  P00005KO9ZO5        100      MERRION RD      NaN      NaN  PANAMA CITY

      STATE  ZIPCODE   PLUS4 LOC_CODE  ...  distanceToNearestCoastFeet  \
5        FL    32401  4366.0      P05  ...                      3758.0
8        FL    32401  4363.0      P05  ...                      4051.0
10       FL    32401  2013.0      P05  ...                      3156.0
11       FL    32401  4326.0      P05  ...                      4500.0
12       FL    32401  2115.0      P05  ...                       260.0
...     ...      ...     ...      ...  ...                         ...
88079    FL    32409  3337.0      P02  ...                      5618.0
88080    FL    32409  3566.0      P05  ...                     40820.0
88081    FL    32409  4015.0      P02  ...                     20469.0
88082    FL    32409  2600.0      P02  ...                     34777.0
88083    FL    32409  1768.0      P05  ...                      2593.0

       livingSquareFootage  totalAssessedValue saleAmount yearBuilt  \
5                      NaN                 NaN        NaN       NaN
8                      NaN                 NaN        NaN       NaN
10                  2116.0            212863.0   213000.0    1955.0
11                  1190.0             41625.0    50000.0    1960.0
12                  3306.0            718548.0        NaN    1948.0
...                    ...                 ...        ...       ...
88079                  NaN                 NaN        NaN       NaN
88080               2280.0             68530.0    65000.0    2004.0
88081                  NaN                 NaN        NaN       NaN
88082                  NaN                 NaN        NaN       NaN
88083               1697.0            253699.0   320000.0    2019.0

       addressLocationElevationFeet  \
5                              18.0
8                              24.0
10                             29.0
11                             19.0
12                             14.0
...                             ...
88079                           5.0
88080                          88.0
88081                          14.0
88082                          73.0
88083                           6.0

                             adultAgeVariableDescription  PSYTEGroupCode  \
5      Majority of adult population aged under 50 and...              11
8      Majority of adult population aged 40-59 (middl...              12
10     Majority of adult population aged 50+ and not ...              12
11     Majority of adult population aged under 39 (yo...               8
12     Majority of adult population aged under 29 (yo...               9
...                                                  ...             ...
88079  Majority of adult population aged 40-59 (middl...               9
88080  Majority of adult population aged under 50 and...              10
88081  Majority of adult population aged 40-59 (middl...               7
88082  Majority of adult population aged under 50 and...              10
88083  Majority of adult population aged under 50 and...              10

                propertyTenureVariableDescription            roofCover
5                                    Mixed tenure                  NaN
8                   Majority of properties rented                  NaN
10          Majority of properties owned outright     COMPOSITION ROLL
11     Majority of properties owned with mortgage  COMPOSITION SHINGLE
12          Majority of properties owned outright             CONCRETE
...                                           ...                  ...
88079       Majority of properties owned outright                  NaN
88080  Majority of properties owned with mortgage              SHINGLE
88081  Majority of properties owned with mortgage                  NaN
88082  Majority of properties owned with mortgage                  NaN
88083  Majority of properties owned with mortgage              SHINGLE

[56709 rows x 28 columns]

### Save the result to a new file

In [8]:
# Save the merged result with all residential addresses to a CSV file
merged_df4.to_csv('data_nofilter.csv', index=False)

# Save the merged result with dropping child residential addresses to a CSV file
filtered_merged_df4.to_csv('data_filtered.csv', index=False)

print("Merged result saved to 'data_nofilter.csv' and 'data_filtered.csv'.")

Merged result saved to 'data_nofilter.csv' and 'data_filtered.csv'.